version: '3'

services:
  server:
    container_name: server8
    image: internetsystemsconsortium/bind9:9.18
    platform: linux/amd64
    ports:
      - "56:53/udp"
      - "56:53/tcp"
    networks:
      bind9_subnet:
        ipv4_address: 192.168.5.1
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind

  cliente:
    container_name: cliente8
    image: alpine:latest
    platform: linux/amd64
    tty: true
    stdin_open: true
    # configuramos para que el cliente use nuestro dns
    dns:
      - 192.168.5.1
    networks:
      bind9_subnet:
        ipv4_address: 192.168.5.2

networks:
  bind9_subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.5.0/24
          gateway: 192.168.5.254
